
trigger:
- main
variables:
   - template: variables/var.yml
stages:
  - template: stages/ci.yml
    parameters:
        containerRegistryServiceConnection: '$containerRegistryServiceConnection'
        imageRepository: '$imageRepository'
        containerRegistry: '$containerRegistry'
        dockerfilePath: '$(Build.SourcesDirectory)/azure-vote/Dockerfile'
        tag: '$(Build.BuildId)'
        k8sNamespace: $k8sNamespace
  # - template: stages/cd.yml


