name: $(BuildDefinitionName)-$(Date:yyyyMMdd)$(Rev:.r)
pool: ubuntu-20.04
trigger:
- main
stages:
  - template: stages/ci.yml
  # - template: stages/cd.yml
variables:
   - template: variables/var.yml
