
trigger:
- main
resources:
- repo: self
parameters:
- name: Environment
  displayName: Deployment Environment
  default: Dev
  values:
  - PPE
  - Dev
stages:
  - stage: CI
  - template: stages/ci.yml
  # - stage: CD
  # - template: stages/cd.yml
variables:
   - template: variables/var.yml
