name: $(BuildDefinitionName)-$(Date:yyyyMMdd)$(Rev:.r)
pool: Hosted Ubuntu 2004
trigger:
- master
stages:
  - template: stages/ci.yml
  # - template: stages/cd.yml
# variables:
   # - template: variables/var.yml
