
trigger:
- main
parameters:
- name: Parameters
  displayName: Test Parameters
  type: object
- name: Environment
  displayName: Deployment Environment
  default: Dev
  values:
  - PPE
  - Dev
stages:
  - template: stages/ci.yml
  # - template: stages/cd.yml
variables:
   - template: variables/var.yml
