
trigger:
- main
resources:
- repo: self
pool:
  vmImage: ubuntu-latest
stages:
  - stage: CI
  - template: stages/ci.yml
  # - stage: CD
  # - template: stages/cd.yml
variables:
   - template: variables/var.yml
