# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

stages:
- stage: Build
  displayName: Build and push docker image
  jobs:  
  - job: Build
    displayName: Build image job
    pool:
      vmImage: ubuntu-20.04
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: votingapptest
    - task: Docker@2
      displayName: Build and push an image to ACR
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: '$(Build.SourcesDirectory)/azure-vote/Dockerfile'
        tags: |
          $(tag)
  - job: GenerateString
    steps:
    - bash:  |
        buildRef="voteapp_$(Build.BuildId)_$(date +'%d%m%y%T')"
        echo "##vso[task.setvariable variable=buildName;isOutput=true]$buildRef"
      name: buildName
  - job: CopyandRenameFile
    dependsOn: GenerateString
    variables:
      varFromGenerateString: $[stageDependencies.GenerateString.outputs['buildName.buildName']]
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: 'azure-vote-all-in-one-redis.yaml'
        TargetFolder: '$(build.artifactstagingdirectory)'
    - bash:  |
        echo 'new file name is $(varFromGenerateString)'
        cp -v azure-vote-all-in-one-redis.yaml '$(varFromGenerateString).yaml'
      name: renameManifest
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
        



